### ISSUE TITLE
Different ID - Walking On The Moon

### ISSUE THREAD

**Issue by AidinAB** [rbhp-espher/rbhp#3]
Upon trying to bundle the harmonies-upgrade for Walking On the Moon by The Police, that upgrade (or song) file had different ID than the original/main song file. It seems the song played out fine (though I was only playing the drums). This should still be checked out and corrected.

**Comment by rbhp-espher** [comment]
Have updated the file and committed a corrected .dta to the 1st quarter 2016 branch.
