### ISSUE TITLE
Red Hot Chili Peppers - Tell Me Baby

### ISSUE THREAD

**Issue by AidinAB** [rbhp-espher/rbhp#4]
I was going to upgrade "Tell Me Baby" by Red Hot Chili Peppers. "Song ID 1005041 doesn't match Upgrade ID 1005159". Game freezes when bringing up song list, no matter which ID I used for upgraded file.

**Comment by rbhp-espher** [comment]
Double-checking this today - I have the song ID as 1005159 in both. Where are you seeing 1005041?
