### ISSUE TITLE
Breaking Benjamin - The Diary of Jane incorrect shortname

### ISSUE THREAD

**Issue by grubextrapolate** [rbhp-espher/rbhp#9]
I don't recall if "shortname" is the official terminology or not... but the first field in the upgrade.dta does not match the songs.dta. songs.dta has the correct "diaryofjane" but the upgrade.dta has "almosteasy". my magical linux rbhp ps3 installer tripped over this in testing just now, so figured I'd report it.

**Comment by rbhp-espher** [comment]
Fixed.
